### ISSUE TITLE
MAYGEN generates wrong valences

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/MAYGEN#68]
This was found with  MAYGREN version 1.6. It generates 582423 isomers for C7H8O3 (Molgen makes 582387 isomers). 
Something went wrong with the valence of oxygen atoms. Attached are two examples SDF files (zipped, since GitHub does not support SDF in issue attachments) where oxygen atoms in the result set have more than two bonds (atom 3 in the first example, atoms 8 and 10 in the second example).

[first.sdf.zip](https://github.com/MehmetAzizYirik/MAYGEN/files/7082727/first.sdf.zip)
[last.sdf.zip](https://github.com/MehmetAzizYirik/MAYGEN/files/7082728/last.sdf.zip)

**Comment by MehmetAzizYirik** [comment]
@steinbeck The number of generated isomers is correct and the same as MOLGEN. In MOLGEN, we need to test with -noaromaticity flag. 

![image](https://user-images.githubusercontent.com/15614358/131479106-e7ddb7c1-c510-47bc-a969-662a0108e419.png)

The issue regarding the oxygen is because of the atom labelling, I need to check. So not because of valences but because of the atom labelling when we write to SDF file. This will be solved when we remove our own SDF rewriters with the CDK SDFWriter. I will look at it today when I set the coordinates for the atoms with CDK Structure Diagram Generator.

**Comment by MehmetAzizYirik** [comment]
@steinbeck I solved the atom labelling issue and tested the formula with the V.1.7. It works, no oxygens with wrong valences.
